name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup-Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy to GH-Pages
        run: npm run deploy
